#!/bin/bash

set -e
set -u


echo "  Creating user and database '$POSTGRES_DB'"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_DB;
  CREATE DATABASE $POSTGRES_DB;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_DB;
EOSQL
