version: "3"
services:
  database:
    image: "postgres:latest"
    restart: always
    environment:
        - POSTGRES_PASSWORD=Pass@word1
        - POSTGRES_DB=tiki
    ports:
      - "5433:5432"
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
